#!/bin/bash
#####################################
# MounterBeast Script
# /etc/NetworkManager/dispatcher.d/02uclavpn
# Copyright 2011 Nathan E. Williams
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Usage:
# This script must be customized for your configuration.
# By default, the script will attempt to mount a CIFS share
# when a specified MAC address is found at the network gateway,
# or over sshfs if the MAC address of the gateway is not the specified MAC.
# e.g. I mount over CIFS to the servers internal IP when at home, and
# over sshfs when away from home.
#
# id gateway mac without physically checking the sticker:
# $ arp -n -a $(ip route show 0.0.0.0/0 | awk '{print $3}') | awk '{print $4}'
#
# Testing:
# up) sudo /etc/NetworkManager/dispatcher.d/02remotemount wlan0 up
# down) sudo /etc/NetworkManager/dispatcher.d/02remotemount wlan0 down
#####################################
#
# Configuration:
#
target_uuid='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
base_dir=/home/xxxx/Shared # base dir of all shared drives

ad=$base_dir/xx.xx.xx.xx
netapp=$base_dir/yy.yy.yy.yy

# ... more shares ...

if [[ "$target_uuid" == "$CONNECTION_UUID" ]]
then
    case "$2" in
        vpn-up)
            mount $ad/dlib
            mount $netapp/DLQueue
            mount $netapp/Masters
            mount $netapp/Projects
            ;;
        vpn-pre-down)
            umount $ad/dlib
            umount $netapp/DLQueue
            umount $netapp/Masters
            umount $netapp/Projects
            ;;
    esac
fi

exit $?

#####################################
# Source: http://askubuntu.com/questions/13963/call-script-after-connecting-to-a-wireless-network/14107
# For more information, see https://docs.library.ucla.edu/display/LIT/Automatically+mount+shared+network+drives+by+connecting+to+UCLA+VPN+on+Ubuntu+14.04+and+16.04
#####################################
